name: Terraform Prod

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  plan:
    runs-on: [self-hosted, linux, pipeline-lab]

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.9"

      - name: Terraform Init
        run: terraform init -backend-config=backends/prod.hcl -reconfigure
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="ministack_endpoint=http://ministack:4566"
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1

  apply:
    needs: plan
    runs-on: [self-hosted, linux, pipeline-lab]
    environment: production

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.9"

      - name: Terraform Init
        run: terraform init -backend-config=backends/prod.hcl -reconfigure
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ministack_endpoint=http://ministack:4566"
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1